<?php

/**
 * Implements hook_preprocess_html().
 */
function gd_theme_preprocess_html(&$variables) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  if ($route_name == 'entity.node.canonical') {
    $node = $route_match->getParameter('node');
    if ($node->id() == 2) {
      $variables['head_title_array'] = array();
      $variables['head_title'] = array();
      $site_name = \Drupal::config('system.site')->get('name');
      $variables['head_title']['title'] = 'Yo ! Hi ! Hola ! สวัสดี ! | ' . $site_name;
      unset($variables['#attached']['html_head']);
    }

  }
}

/**
 * Implements hook_preprocess_node().
 */
function gd_theme_preprocess_node(&$variables, $hook) {
  $include = drupal_get_path('module', 'gd_theme') .'/includes/' . $variables['node']->bundle() . '.inc';
  if (file_exists($include)) {
    require_once $include;
  }

  $function = __FUNCTION__ . '_' . $variables['node']->bundle();
  if (function_exists($function)) {
    $function($variables, $hook);
  }

  if ($variables['view_mode'] == 'full') {
  }

  $variables['attributes']['class'][] = 'view-mode-' . str_replace('_', '-', $variables['view_mode']);
  $variables['attributes']['class'][] = 'node';
  $variables['attributes']['class'][] = 'node-' . $variables['node']->bundle();
}
